name: CI
on:
  push:
    branches:
      - develop
jobs:
  ci:
    name: Test - Unit & Integration  & SonarCloud Scan
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Unit & Integration Tests
        run: mvn -B verify # -B: --batch-mode
      - name: Sonar
        if: success() # always() failure() success()
        run: >
          mvn -B verify -DskipTests sonar:sonar
          -Dsonar.projectKey=tfm-spring
          -Dsonar.organization=sucrox
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=$SONAR_TFM_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TFM_TOKEN }}